name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <=3.5.4"
  flutter: 3.24.5

dependencies:
  flutter_html:
  flutter_html_all:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg