name: flutter_html_svg
description: This extension package allows the <svg> tag and svg-based img sources to be rendered using the flutter_html package
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=3.0.0 <=3.5.4"
  flutter: 3.24.5

dependencies:
  flutter:
    sdk: flutter
  html: 
  flutter_html: ^3.0.0
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  meta: 

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - svg
  - images
