name: flutter_html_table
description: This extension package allows the <table> tag to be rendered using the flutter_html package

version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=3.0.0 <=3.5.4"
  flutter: 3.24.5

dependencies:
  flutter:
    sdk: flutter
  html: 
  flutter_html: 
  flutter_layout_grid: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

funding:
  - https://github.com/sponsors/Sub6Resources

topics:
  - html
  - css
  - table
  - layout
